#!/bin/sh

export system64=$(uname -m)

# line added by shardul
cd $HOME/Android/Programs/FlashTool
# export BASEDIR=$(dirname $0)
# cd $BASEDIR

if test -z "${JAVA_HOME}"
then
	if test "${system64}" = "x86_64"
	then
		export JAVA_HOME=./x10flasher_lib/linjre64
	else
		export JAVA_HOME=./x10flasher_lib/linjre32
	fi
	echo "JAVA_HOME not set. Using default value : ${JAVA_HOME}"
fi

chmod 755 ./x10flasher_lib/adb.linux
chmod 755 ./x10flasher_lib/fastboot.linux
chmod 755 ./x10flasher_lib/adb.mac
chmod 755 ./x10flasher_lib/fastboot.mac
chmod 755 ./x10flasher_lib/bin2elf
chmod 755 ./x10flasher_lib/bin2sin
chmod 755 ./x10flasher_lib/fastboot.mac

if test -e ${JAVA_HOME}/bin/java
then
	$JAVA_HOME/bin/java -Xms128m -Xmx512m -Duser.country=US -Duser.language=en -jar x10flasher.jar
else
	echo "No Java in specified path in JAVA_HOME=${JAVA_HOME}"
	echo "Set the variable to a valid Java installation"
fi
